import React from "react";
import "./styles/color.css";
import "./styles/font.css";
import App from "./App";
import "./styles/index.css";
import "./styles/tailwind.css";
import { createRoot } from "react-dom/client";
document.body.innerHTML = '<div id="app"></div>';
const root = createRoot(document.getElementById("app"));
root.render(<App />);